name: Deploy via FTP to cowoboilerplate.carlwebdev.com

on:
  push:
    branches:
      - main  # Canvia-ho si treballes amb una altra branca

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.carlwebdev.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /cowoboilerplate.carlwebdev.com/public_html/
          local-dir: ./
          exclude: |
            */.git
            */.github
            */node_modules/*
            **/sftp.json
